version: '2'

services:
 postgres:
  image: library/postgres
  environment:
   POSTGRES_USER: 'admin'
   POSTGRES_PASSWORD: '1234'
  ports:
   - "5432:5432"
  volumes:
   - ./../politbase-data:/var/lib/postgresql/data
   - ./sql:/tmp
